# data
data_dir: '/home/jhlee/Explainable_Movie_Rating_Classifier/data/keT5_summarization/'
# data_dir: '/home/jhlee/Explainable_Movie_Rating_Classifier/data/'

num_gpus: 1
batch_size: 8
num_workers: 4

lr: 1e-4 # 3e-5
weight_decay: 0.01
adam_epsilon: 0.99
warmup_steps: 100

model_name_or_path: 'beomi/KcELECTRA-base-v2022'
num_labels: 4
max_length: 512

# data
data:
  data_dir: ${data_dir}

  dataloader_params:
    batch_size: ${batch_size}
    num_workers: ${num_workers}
    shuffle: False

# trainer
trainer:
  accelerator: "auto"
  devices: ${num_gpus}
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  accumulate_grad_batches: 1
  max_epochs: 300
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true

# wandb logger
project: 유해성
name: 512_cut-kcelectra-base-v2022

checkpoint_dir: "model_save/"

hydra:
  run:
    dir: "outputs/${name}"

# saved model_path
test_model_path: "/home/jhlee/Explainable_Movie_Rating_Classifier/outputs/keT5sum_infer-kcelectra-base-v2022/model_save/model_epoch=283-val_loss=1.28.ckpt"
test_save_path:
